#cloud-config
packages:
  - apache2
  - mkdocs
  - qemu-guest-agent
  - mc

users:
  - default
  - name: ill
    gecos: ILL User
    shell: /bin/bash
    primary_group: users
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHztpdM8jH0W96dLiHtgNm+LyoQIpdzXAlXGIIl0Mjgr illro@Pauls-MacBook-Pro

runcmd:
  - echo "Hello! and welcome to this Proxmox server!" > /home/ill/hello.txt
  - sudo chown ill:users /home/ill/hello.txt
  - sudo systemctl enable qemu-guest-agent
  - sudo systemctl start qemu-guest-agent
  - sudo systemctl enable apache2
  - sudo systemctl restart apache2
  - sudo mkdir /home/ill/mkdocs
  - sudo chown -R ill:users /home/ill/mkdocs
  - cd /home/ill/mkdocs
  - sudo mkdocs new mkdocs-project
  - cd mkdocs-project
  - sudo mkdocs build
  - sudo rm /var/www/html/index.html
  - sudo cp -R site/* /var/www/html
